version: 2
jobs:
  verify:
    working_directory: ~/repo
    docker:
      - image: circleci/node:7.10
        environment:
            - NODE_ENV="prod"
    steps:
      - checkout
      - run:
          name: Configure NPM
          command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> ~/.npmrc
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Verify
          command: npm run verify

  deploy:
    working_directory: ~/repo
    docker:
      - image: circleci/node:6.10-browsers
    steps:
      - checkout
      - run:
          name: Configure NPM
          command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> ~/.npmrc
      - run:
          name: Build
          command: npm run build
      - run:
          name: Publish to NPM
          command: npm publish

workflows:
  version: 2
  verify-and-deploy:
    jobs:
      - verify
      - deploy:
          requires:
            - verify
          filters:
            branches:
              only: master
